/**
 * 
 */
package enums;

/**
 * TypeNode.java. <p>
 * @author  Vincent Cephirins
 * @version 1.0, 15 nov. 2010
 * <li>Creation</>
 */

public enum TypeNode {
    NULL, ALIAS, IDENT,
    BREAK_ON,
    COLUMN, CONST, EXPR, EXPR_COND,
    DEFINE, 
    ALIAS_FILE, FILE, TYPE_FILE,
    FLAG, FUNCTION, FOR, FORMAT, FROM,
    GROUP_BY,
    INTERVAL,
    KEYWORD,
    LIST_ALIAS, LIST_FILE,
    LIST_FMT, LIST_FMT_ASCII, LIST_FMT_BIN, LIST_IDENT,
    LIST_COLUMN, LIST_INTERVAL, LIST_EXPR, LIST_REF, 
    REQUEST, ROWID, ROWNUM,
    PRINT, SELECT, SELECT_FOR, SELECT_WITH, SELECT_DEFINE, SELECT_COLUMN, 
    SELECT_FROM, SELECT_WHERE, SELECT_GROUP_BY, SELECT_BREAK_ON, SELECT_FORMAT,
    TYPE, WHERE, WITH, QUIT,
    FMT_ASCII, FMT_BIN, LIST_FMT_ASCII_SEP, 
    TYPE_VALUE, TYPE_MATH, TYPE_COND, TYPE_DATE;
}
